#pragma once

#ifndef P5_SLAUGHTERHOUSE_GLOBAL_EXTERN
#define P5_SLAUGHTERHOUSE_GLOBAL_EXTERN extern
#endif // P5_SLAUGHTERHOUSE_GLOBAL_EXTERN

#ifndef P5_SLAUGHTERHOUSE_GLOBAL_EXTERN_C
#ifdef __cplusplus
#define P5_SLAUGHTERHOUSE_GLOBAL_EXTERN_C P5_SLAUGHTERHOUSE_GLOBAL_EXTERN "C"
#else
#define P5_SLAUGHTERHOUSE_GLOBAL_EXTERN_C P5_SLAUGHTERHOUSE_GLOBAL_EXTERN
#endif // __cplusplus
#endif // P5_SLAUGHTERHOUSE_GLOBAL_EXTERN_C

#ifndef P5_SLAUGHTERHOUSE_GLOBAL_CDECL
#if (defined _MSC_VER) || (defined __MINGW32__)
#define P5_SLAUGHTERHOUSE_GLOBAL_CDECL __cdecl
#elif defined __GNUC__
#define P5_SLAUGHTERHOUSE_GLOBAL_CDECL __attribute__((cdecl))
#else
#error "Unsupported compiler"
#endif
#endif // P5_SLAUGHTERHOUSE_GLOBAL_CDECL

#ifndef P5_SLAUGHTERHOUSE_GLOBAL_WINAPI
#ifdef _WIN32
#define P5_SLAUGHTERHOUSE_GLOBAL_WINAPI WINAPI
#else
#define P5_SLAUGHTERHOUSE_GLOBAL_WINAPI
#endif // _WIN32
#endif // P5_SLAUGHTERHOUSE_GLOBAL_WINAPI

#ifndef P5_SLAUGHTERHOUSE_GLOBAL_EXPORT
#ifdef _MSC_VER
#define P5_SLAUGHTERHOUSE_GLOBAL_EXPORT __declspec(dllexport)
#elif defined __MINGW32__
#define P5_SLAUGHTERHOUSE_GLOBAL_EXPORT __declspec(dllexport)
#elif defined __GNUC__
#define P5_SLAUGHTERHOUSE_GLOBAL_EXPORT __attribute__((visibility("default")))
#else
#error "Unsupported compiler"
#endif
#endif // P5_SLAUGHTERHOUSE_GLOBAL_EXPORT

#ifndef P5_SLAUGHTERHOUSE_GLOBAL_IMPORT
#ifdef _MSC_VER
#define P5_SLAUGHTERHOUSE_GLOBAL_IMPORT __declspec(dllimport)
#elif defined __MINGW32__
#define P5_SLAUGHTERHOUSE_GLOBAL_IMPORT __declspec(dllimport)
#elif defined __GNUC__
#define P5_SLAUGHTERHOUSE_GLOBAL_IMPORT
#else
#error "Unsupported compiler"
#endif
#endif // P5_SLAUGHTERHOUSE_GLOBAL_IMPORT

#ifndef P5_SLAUGHTERHOUSE_GLOBAL_API
#if defined P5_SLAUGHTERHOUSE_IMPLEMENTATION
#define P5_SLAUGHTERHOUSE_GLOBAL_API P5_SLAUGHTERHOUSE_GLOBAL_EXPORT
#else
#define P5_SLAUGHTERHOUSE_GLOBAL_API P5_SLAUGHTERHOUSE_GLOBAL_IMPORT
#endif // P5_SLAUGHTERHOUSE_IMPLEMENTATION
#endif // P5_SLAUGHTERHOUSE_GLOBAL_API
