name: main

on: ["push", "pull_request"]
jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        compiler: [cl, g++, clang++]
        build_type: [Release, Debug]
        include:
          - os: windows-latest
            compiler: cl
            compiler_flags: "/EHsc /WX"
          - os: ubuntu-latest
            compiler: g++
            compiler_flags: "-Werror -Wall -Weffc++ -Wextra -Wpedantic"
          - os: ubuntu-latest
            compiler: clang++
            compiler_flags: "-Werror -Wall -Weffc++ -Wextra -Wpedantic"

    steps:
    - if: matrix.compiler == 'cl'
      run: |
        # installing conan
        pip3 install --upgrade conan
        conan profile detect

    - if: matrix.compiler != 'cl'
      run: sudo apt install --assume-yes libboost-all-dev

    - if: matrix.compiler == 'cl'
      shell: bash
      run: |
        # conanfile.txt
        cat >conanfile.txt <<EOF
        [requires]
        boost/[>=1.83.0]
        [generators]
        CMakeDeps
        CMakeToolchain
        [layout]
        cmake_layout
        EOF
        conan install conanfile.txt --build=missing --settings:all compiler.cppstd=20 --settings:all build_type='${{ matrix.build_type }}'
        rm --force conanfile.txt

    - uses: actions/checkout@v3
      with:
        path: sources

    - shell: bash
      run: |
        # initializing cmake
        if [ xclx == x'${{ matrix.compiler }}'x ]; then
          cp build/generators/CMakePresets.json sources/
          cmake -S sources -B build --preset conan-default
        else
          cmake -S sources -B build -DCMAKE_CXX_COMPILER='${{ matrix.compiler }}'
        fi

    - if: matrix.compiler != 'cl'
      run: cmake -S sources -B build -DCMAKE_BUILD_TYPE='${{ matrix.build_type }}'

    - if: matrix.compiler_flags != ''
      run: cmake -S sources -B build -DCMAKE_CXX_FLAGS='${{ matrix.compiler_flags }}'

    - run: cmake --build build --config '${{ matrix.build_type }}'

    - working-directory: build
      run: ctest --output-on-failure --build-config '${{ matrix.build_type }}'

    - uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.compiler }}-${{ matrix.build_type }}
        path: build
